/**
 * Infrahub-API
 * Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserConsent from './UserConsent';
import UserConsentEvent from './UserConsentEvent';

/**
 * The ConsentEventsResponse model module.
 * @module model/ConsentEventsResponse
 * @version v1.52.3-alpha
 */
class ConsentEventsResponse {
    /**
     * Constructs a new <code>ConsentEventsResponse</code>.
     * @alias module:model/ConsentEventsResponse
     */
    constructor() { 
        
        ConsentEventsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConsentEventsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConsentEventsResponse} obj Optional instance to populate.
     * @return {module:model/ConsentEventsResponse} The populated <code>ConsentEventsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConsentEventsResponse();

            if (data.hasOwnProperty('consent')) {
                obj['consent'] = UserConsent.constructFromObject(data['consent']);
            }
            if (data.hasOwnProperty('events')) {
                obj['events'] = ApiClient.convertToType(data['events'], [UserConsentEvent]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ConsentEventsResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ConsentEventsResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `consent`
        if (data['consent']) { // data not null
          UserConsent.validateJSON(data['consent']);
        }
        if (data['events']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['events'])) {
                throw new Error("Expected the field `events` to be an array in the JSON data but got " + data['events']);
            }
            // validate the optional field `events` (array)
            for (const item of data['events']) {
                UserConsentEvent.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {module:model/UserConsent} consent
 */
ConsentEventsResponse.prototype['consent'] = undefined;

/**
 * @member {Array.<module:model/UserConsentEvent>} events
 */
ConsentEventsResponse.prototype['events'] = undefined;






export default ConsentEventsResponse;

