/**
 * Infrahub-API
 * Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FieldChange from './FieldChange';

/**
 * The ContractChangePayload model module.
 * @module model/ContractChangePayload
 * @version v1.25.0-alpha
 */
class ContractChangePayload {
    /**
     * Constructs a new <code>ContractChangePayload</code>.
     * @alias module:model/ContractChangePayload
     * @param id {Number} The ID of the contract
     * @param orgId {Number} The ORG ID of the contract
     * @param type {String} Purpose of the change: created, deleted, expired, or updated
     */
    constructor(id, orgId, type) { 
        
        ContractChangePayload.initialize(this, id, orgId, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, orgId, type) { 
        obj['id'] = id;
        obj['org_id'] = orgId;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>ContractChangePayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContractChangePayload} obj Optional instance to populate.
     * @return {module:model/ContractChangePayload} The populated <code>ContractChangePayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContractChangePayload();

            if (data.hasOwnProperty('changes')) {
                obj['changes'] = ApiClient.convertToType(data['changes'], [FieldChange]);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('org_id')) {
                obj['org_id'] = ApiClient.convertToType(data['org_id'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ContractChangePayload</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ContractChangePayload</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ContractChangePayload.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['changes']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['changes'])) {
                throw new Error("Expected the field `changes` to be an array in the JSON data but got " + data['changes']);
            }
            // validate the optional field `changes` (array)
            for (const item of data['changes']) {
                FieldChange.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }

        return true;
    }


}

ContractChangePayload.RequiredProperties = ["id", "org_id", "type"];

/**
 * List of field changes for 'updated' type
 * @member {Array.<module:model/FieldChange>} changes
 */
ContractChangePayload.prototype['changes'] = undefined;

/**
 * The ID of the contract
 * @member {Number} id
 */
ContractChangePayload.prototype['id'] = undefined;

/**
 * The ORG ID of the contract
 * @member {Number} org_id
 */
ContractChangePayload.prototype['org_id'] = undefined;

/**
 * Purpose of the change: created, deleted, expired, or updated
 * @member {String} type
 */
ContractChangePayload.prototype['type'] = undefined;






export default ContractChangePayload;

