/**
 * Infrahub-API
 * Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NodeStocksPayload model module.
 * @module model/NodeStocksPayload
 * @version v1.25.0-alpha
 */
class NodeStocksPayload {
    /**
     * Constructs a new <code>NodeStocksPayload</code>.
     * @alias module:model/NodeStocksPayload
     * @param inUse {Number} 
     * @param total {Number} 
     * @param type {String} 
     */
    constructor(inUse, total, type) { 
        
        NodeStocksPayload.initialize(this, inUse, total, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, inUse, total, type) { 
        obj['in_use'] = inUse;
        obj['total'] = total;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>NodeStocksPayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NodeStocksPayload} obj Optional instance to populate.
     * @return {module:model/NodeStocksPayload} The populated <code>NodeStocksPayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NodeStocksPayload();

            if (data.hasOwnProperty('in_use')) {
                obj['in_use'] = ApiClient.convertToType(data['in_use'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>NodeStocksPayload</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>NodeStocksPayload</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of NodeStocksPayload.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }

        return true;
    }


}

NodeStocksPayload.RequiredProperties = ["in_use", "total", "type"];

/**
 * @member {Number} in_use
 */
NodeStocksPayload.prototype['in_use'] = undefined;

/**
 * @member {String} name
 */
NodeStocksPayload.prototype['name'] = undefined;

/**
 * @member {Number} total
 */
NodeStocksPayload.prototype['total'] = undefined;

/**
 * @member {String} type
 */
NodeStocksPayload.prototype['type'] = undefined;






export default NodeStocksPayload;

