/**
 * Infrahub-API
 * Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ObjectStorageRegionResponse from './ObjectStorageRegionResponse';

/**
 * The ObjectStorageRegionListResponse model module.
 * @module model/ObjectStorageRegionListResponse
 * @version v1.47.0-alpha
 */
class ObjectStorageRegionListResponse {
    /**
     * Constructs a new <code>ObjectStorageRegionListResponse</code>.
     * @alias module:model/ObjectStorageRegionListResponse
     * @param regions {Array.<module:model/ObjectStorageRegionResponse>} 
     */
    constructor(regions) { 
        
        ObjectStorageRegionListResponse.initialize(this, regions);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, regions) { 
        obj['regions'] = regions;
    }

    /**
     * Constructs a <code>ObjectStorageRegionListResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ObjectStorageRegionListResponse} obj Optional instance to populate.
     * @return {module:model/ObjectStorageRegionListResponse} The populated <code>ObjectStorageRegionListResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ObjectStorageRegionListResponse();

            if (data.hasOwnProperty('regions')) {
                obj['regions'] = ApiClient.convertToType(data['regions'], [ObjectStorageRegionResponse]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ObjectStorageRegionListResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ObjectStorageRegionListResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ObjectStorageRegionListResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['regions']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['regions'])) {
                throw new Error("Expected the field `regions` to be an array in the JSON data but got " + data['regions']);
            }
            // validate the optional field `regions` (array)
            for (const item of data['regions']) {
                ObjectStorageRegionResponse.validateJSON(item);
            };
        }

        return true;
    }


}

ObjectStorageRegionListResponse.RequiredProperties = ["regions"];

/**
 * @member {Array.<module:model/ObjectStorageRegionResponse>} regions
 */
ObjectStorageRegionListResponse.prototype['regions'] = undefined;






export default ObjectStorageRegionListResponse;

