/**
 * Infrahub-API
 * Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ObjectStorageRegionsEnum from './ObjectStorageRegionsEnum';

/**
 * The ObjectStorageAccessKeyCreateResponse model module.
 * @module model/ObjectStorageAccessKeyCreateResponse
 * @version v1.46.4-alpha
 */
class ObjectStorageAccessKeyCreateResponse {
    /**
     * Constructs a new <code>ObjectStorageAccessKeyCreateResponse</code>.
     * @alias module:model/ObjectStorageAccessKeyCreateResponse
     * @param accessKey {String} 
     * @param createdAt {Date} 
     * @param id {Number} 
     * @param region {module:model/ObjectStorageRegionsEnum} 
     * @param secretKey {String} 
     * @param userId {Number} 
     */
    constructor(accessKey, createdAt, id, region, secretKey, userId) { 
        
        ObjectStorageAccessKeyCreateResponse.initialize(this, accessKey, createdAt, id, region, secretKey, userId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, accessKey, createdAt, id, region, secretKey, userId) { 
        obj['access_key'] = accessKey;
        obj['created_at'] = createdAt;
        obj['id'] = id;
        obj['region'] = region;
        obj['secret_key'] = secretKey;
        obj['user_id'] = userId;
    }

    /**
     * Constructs a <code>ObjectStorageAccessKeyCreateResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ObjectStorageAccessKeyCreateResponse} obj Optional instance to populate.
     * @return {module:model/ObjectStorageAccessKeyCreateResponse} The populated <code>ObjectStorageAccessKeyCreateResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ObjectStorageAccessKeyCreateResponse();

            if (data.hasOwnProperty('access_key')) {
                obj['access_key'] = ApiClient.convertToType(data['access_key'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], Object);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('region')) {
                obj['region'] = ObjectStorageRegionsEnum.constructFromObject(data['region']);
            }
            if (data.hasOwnProperty('secret_key')) {
                obj['secret_key'] = ApiClient.convertToType(data['secret_key'], 'String');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ObjectStorageAccessKeyCreateResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ObjectStorageAccessKeyCreateResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ObjectStorageAccessKeyCreateResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['access_key'] && !(typeof data['access_key'] === 'string' || data['access_key'] instanceof String)) {
            throw new Error("Expected the field `access_key` to be a primitive type in the JSON string but got " + data['access_key']);
        }
        // ensure the json data is a string
        if (data['secret_key'] && !(typeof data['secret_key'] === 'string' || data['secret_key'] instanceof String)) {
            throw new Error("Expected the field `secret_key` to be a primitive type in the JSON string but got " + data['secret_key']);
        }

        return true;
    }


}

ObjectStorageAccessKeyCreateResponse.RequiredProperties = ["access_key", "created_at", "id", "region", "secret_key", "user_id"];

/**
 * @member {String} access_key
 */
ObjectStorageAccessKeyCreateResponse.prototype['access_key'] = undefined;

/**
 * @member {Date} created_at
 */
ObjectStorageAccessKeyCreateResponse.prototype['created_at'] = undefined;

/**
 * @member {Object} description
 */
ObjectStorageAccessKeyCreateResponse.prototype['description'] = undefined;

/**
 * @member {Number} id
 */
ObjectStorageAccessKeyCreateResponse.prototype['id'] = undefined;

/**
 * @member {module:model/ObjectStorageRegionsEnum} region
 */
ObjectStorageAccessKeyCreateResponse.prototype['region'] = undefined;

/**
 * @member {String} secret_key
 */
ObjectStorageAccessKeyCreateResponse.prototype['secret_key'] = undefined;

/**
 * @member {Number} user_id
 */
ObjectStorageAccessKeyCreateResponse.prototype['user_id'] = undefined;






export default ObjectStorageAccessKeyCreateResponse;

