/**
 * Infrahub-API
 * Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ObjectStorageRegionsEnum from './ObjectStorageRegionsEnum';

/**
 * The ObjectStorageBucketResponse model module.
 * @module model/ObjectStorageBucketResponse
 * @version v1.46.4-alpha
 */
class ObjectStorageBucketResponse {
    /**
     * Constructs a new <code>ObjectStorageBucketResponse</code>.
     * @alias module:model/ObjectStorageBucketResponse
     * @param createdAt {Date} 
     * @param endpoint {String} 
     * @param name {String} 
     * @param numObjects {Number} Number of objects
     * @param region {module:model/ObjectStorageRegionsEnum} 
     * @param sizeBytes {Number} Accumulated size in bytes
     * @param sizeBytesActual {Number} Size utilized in bytes
     */
    constructor(createdAt, endpoint, name, numObjects, region, sizeBytes, sizeBytesActual) { 
        
        ObjectStorageBucketResponse.initialize(this, createdAt, endpoint, name, numObjects, region, sizeBytes, sizeBytesActual);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, createdAt, endpoint, name, numObjects, region, sizeBytes, sizeBytesActual) { 
        obj['created_at'] = createdAt;
        obj['endpoint'] = endpoint;
        obj['name'] = name;
        obj['num_objects'] = numObjects;
        obj['region'] = region;
        obj['size_bytes'] = sizeBytes;
        obj['size_bytes_actual'] = sizeBytesActual;
    }

    /**
     * Constructs a <code>ObjectStorageBucketResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ObjectStorageBucketResponse} obj Optional instance to populate.
     * @return {module:model/ObjectStorageBucketResponse} The populated <code>ObjectStorageBucketResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ObjectStorageBucketResponse();

            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('endpoint')) {
                obj['endpoint'] = ApiClient.convertToType(data['endpoint'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('num_objects')) {
                obj['num_objects'] = ApiClient.convertToType(data['num_objects'], 'Number');
            }
            if (data.hasOwnProperty('region')) {
                obj['region'] = ObjectStorageRegionsEnum.constructFromObject(data['region']);
            }
            if (data.hasOwnProperty('size_bytes')) {
                obj['size_bytes'] = ApiClient.convertToType(data['size_bytes'], 'Number');
            }
            if (data.hasOwnProperty('size_bytes_actual')) {
                obj['size_bytes_actual'] = ApiClient.convertToType(data['size_bytes_actual'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ObjectStorageBucketResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ObjectStorageBucketResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ObjectStorageBucketResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['endpoint'] && !(typeof data['endpoint'] === 'string' || data['endpoint'] instanceof String)) {
            throw new Error("Expected the field `endpoint` to be a primitive type in the JSON string but got " + data['endpoint']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

ObjectStorageBucketResponse.RequiredProperties = ["created_at", "endpoint", "name", "num_objects", "region", "size_bytes", "size_bytes_actual"];

/**
 * @member {Date} created_at
 */
ObjectStorageBucketResponse.prototype['created_at'] = undefined;

/**
 * @member {String} endpoint
 */
ObjectStorageBucketResponse.prototype['endpoint'] = undefined;

/**
 * @member {String} name
 */
ObjectStorageBucketResponse.prototype['name'] = undefined;

/**
 * Number of objects
 * @member {Number} num_objects
 */
ObjectStorageBucketResponse.prototype['num_objects'] = undefined;

/**
 * @member {module:model/ObjectStorageRegionsEnum} region
 */
ObjectStorageBucketResponse.prototype['region'] = undefined;

/**
 * Accumulated size in bytes
 * @member {Number} size_bytes
 */
ObjectStorageBucketResponse.prototype['size_bytes'] = undefined;

/**
 * Size utilized in bytes
 * @member {Number} size_bytes_actual
 */
ObjectStorageBucketResponse.prototype['size_bytes_actual'] = undefined;






export default ObjectStorageBucketResponse;

