/**
 * Infrahub-API
 * Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Colors from './Colors';
import Logos from './Logos';
import URIs from './URIs';

/**
 * The PartnerConfig model module.
 * @module model/PartnerConfig
 * @version v1.43.0-alpha
 */
class PartnerConfig {
    /**
     * Constructs a new <code>PartnerConfig</code>.
     * @alias module:model/PartnerConfig
     * @param name {String} 
     * @param userType {String} 
     */
    constructor(name, userType) { 
        
        PartnerConfig.initialize(this, name, userType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, userType) { 
        obj['name'] = name;
        obj['user_type'] = userType;
    }

    /**
     * Constructs a <code>PartnerConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PartnerConfig} obj Optional instance to populate.
     * @return {module:model/PartnerConfig} The populated <code>PartnerConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PartnerConfig();

            if (data.hasOwnProperty('background_image_url')) {
                obj['background_image_url'] = ApiClient.convertToType(data['background_image_url'], 'String');
            }
            if (data.hasOwnProperty('colors')) {
                obj['colors'] = Colors.constructFromObject(data['colors']);
            }
            if (data.hasOwnProperty('logos')) {
                obj['logos'] = Logos.constructFromObject(data['logos']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('support_email')) {
                obj['support_email'] = ApiClient.convertToType(data['support_email'], 'String');
            }
            if (data.hasOwnProperty('uris')) {
                obj['uris'] = URIs.constructFromObject(data['uris']);
            }
            if (data.hasOwnProperty('user_type')) {
                obj['user_type'] = ApiClient.convertToType(data['user_type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PartnerConfig</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PartnerConfig</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PartnerConfig.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['background_image_url'] && !(typeof data['background_image_url'] === 'string' || data['background_image_url'] instanceof String)) {
            throw new Error("Expected the field `background_image_url` to be a primitive type in the JSON string but got " + data['background_image_url']);
        }
        // validate the optional field `colors`
        if (data['colors']) { // data not null
          Colors.validateJSON(data['colors']);
        }
        // validate the optional field `logos`
        if (data['logos']) { // data not null
          Logos.validateJSON(data['logos']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['support_email'] && !(typeof data['support_email'] === 'string' || data['support_email'] instanceof String)) {
            throw new Error("Expected the field `support_email` to be a primitive type in the JSON string but got " + data['support_email']);
        }
        // validate the optional field `uris`
        if (data['uris']) { // data not null
          URIs.validateJSON(data['uris']);
        }
        // ensure the json data is a string
        if (data['user_type'] && !(typeof data['user_type'] === 'string' || data['user_type'] instanceof String)) {
            throw new Error("Expected the field `user_type` to be a primitive type in the JSON string but got " + data['user_type']);
        }

        return true;
    }


}

PartnerConfig.RequiredProperties = ["name", "user_type"];

/**
 * @member {String} background_image_url
 */
PartnerConfig.prototype['background_image_url'] = undefined;

/**
 * @member {module:model/Colors} colors
 */
PartnerConfig.prototype['colors'] = undefined;

/**
 * @member {module:model/Logos} logos
 */
PartnerConfig.prototype['logos'] = undefined;

/**
 * @member {String} name
 */
PartnerConfig.prototype['name'] = undefined;

/**
 * @member {String} support_email
 */
PartnerConfig.prototype['support_email'] = undefined;

/**
 * @member {module:model/URIs} uris
 */
PartnerConfig.prototype['uris'] = undefined;

/**
 * @member {String} user_type
 */
PartnerConfig.prototype['user_type'] = undefined;






export default PartnerConfig;

