/**
 * Infrahub-API
 * Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponseModel from '../model/ErrorResponseModel';
import InstanceEvents from '../model/InstanceEvents';

/**
* VirtualMachineEvents service.
* @module api/VirtualMachineEventsApi
* @version v1.25.0-alpha
*/
export default class VirtualMachineEventsApi {

    /**
    * Constructs a new VirtualMachineEventsApi. 
    * @alias module:api/VirtualMachineEventsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * List virtual machine events
     * Retrieves a list of all events in a virtual machine's history, which records actions performed on the specified virtual machine. Include the virtual machine ID in the path to retrieve the history of events. For more details on virtual machine events history, [**click here**](https://infrahub-doc.nexgencloud.com/docs/virtual-machines/vm-performance-metrics-and-events-history#events-history).
     * @param {String} virtualMachineId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InstanceEvents} and HTTP response
     */
    listVirtualMachineEventsWithHttpInfo(virtualMachineId) {
      let postBody = null;
      // verify the required parameter 'virtualMachineId' is set
      if (virtualMachineId === undefined || virtualMachineId === null) {
        throw new Error("Missing the required parameter 'virtualMachineId' when calling listVirtualMachineEvents");
      }

      let pathParams = {
        'virtual_machine_id': virtualMachineId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey', 'accessToken'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InstanceEvents;
      return this.apiClient.callApi(
        '/core/virtual-machines/{virtual_machine_id}/events', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * List virtual machine events
     * Retrieves a list of all events in a virtual machine's history, which records actions performed on the specified virtual machine. Include the virtual machine ID in the path to retrieve the history of events. For more details on virtual machine events history, [**click here**](https://infrahub-doc.nexgencloud.com/docs/virtual-machines/vm-performance-metrics-and-events-history#events-history).
     * @param {String} virtualMachineId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InstanceEvents}
     */
    listVirtualMachineEvents(virtualMachineId) {
      return this.listVirtualMachineEventsWithHttpInfo(virtualMachineId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
