/**
 * Infrahub-API
 * Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HyperstackApi);
  }
}(this, function(expect, HyperstackApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HyperstackApi.ContractDiscountPlanFields();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ContractDiscountPlanFields', function() {
    it('should create an instance of ContractDiscountPlanFields', function() {
      // uncomment below and update the code to test ContractDiscountPlanFields
      //var instance = new HyperstackApi.ContractDiscountPlanFields();
      //expect(instance).to.be.a(HyperstackApi.ContractDiscountPlanFields);
    });

    it('should have the property discountAmount (base name: "discount_amount")', function() {
      // uncomment below and update the code to test the property discountAmount
      //var instance = new HyperstackApi.ContractDiscountPlanFields();
      //expect(instance).to.be();
    });

    it('should have the property discountCode (base name: "discount_code")', function() {
      // uncomment below and update the code to test the property discountCode
      //var instance = new HyperstackApi.ContractDiscountPlanFields();
      //expect(instance).to.be();
    });

    it('should have the property discountPercent (base name: "discount_percent")', function() {
      // uncomment below and update the code to test the property discountPercent
      //var instance = new HyperstackApi.ContractDiscountPlanFields();
      //expect(instance).to.be();
    });

    it('should have the property discountStatus (base name: "discount_status")', function() {
      // uncomment below and update the code to test the property discountStatus
      //var instance = new HyperstackApi.ContractDiscountPlanFields();
      //expect(instance).to.be();
    });

    it('should have the property discountType (base name: "discount_type")', function() {
      // uncomment below and update the code to test the property discountType
      //var instance = new HyperstackApi.ContractDiscountPlanFields();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new HyperstackApi.ContractDiscountPlanFields();
      //expect(instance).to.be();
    });

    it('should have the property resourceCount (base name: "resource_count")', function() {
      // uncomment below and update the code to test the property resourceCount
      //var instance = new HyperstackApi.ContractDiscountPlanFields();
      //expect(instance).to.be();
    });

    it('should have the property resourceId (base name: "resource_id")', function() {
      // uncomment below and update the code to test the property resourceId
      //var instance = new HyperstackApi.ContractDiscountPlanFields();
      //expect(instance).to.be();
    });

    it('should have the property resourceName (base name: "resource_name")', function() {
      // uncomment below and update the code to test the property resourceName
      //var instance = new HyperstackApi.ContractDiscountPlanFields();
      //expect(instance).to.be();
    });

  });

}));
