/**
 * Infrahub-API
 * Leverage the Infrahub API and Hyperstack platform to easily create, manage, and scale powerful GPU virtual machines and their associated resources.   Access this SDK to automate the deployment of your workloads and streamline your infrastructure management.  To contribute, please raise an issue with a bug report, feature request, feedback, or general inquiry.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HyperstackApi);
  }
}(this, function(expect, HyperstackApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HyperstackApi.BillingApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BillingApi', function() {
    describe('getLastDayCost', function() {
      it('should call getLastDayCost successfully', function(done) {
        //uncomment below and update the code to test getLastDayCost
        //instance.getLastDayCost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOrganizationThreshold', function() {
      it('should call getOrganizationThreshold successfully', function(done) {
        //uncomment below and update the code to test getOrganizationThreshold
        //instance.getOrganizationThreshold(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUsage2', function() {
      it('should call getUsage2 successfully', function(done) {
        //uncomment below and update the code to test getUsage2
        //instance.getUsage2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingBucketDetailsGraph', function() {
      it('should call getUserBillingBucketDetailsGraph successfully', function(done) {
        //uncomment below and update the code to test getUserBillingBucketDetailsGraph
        //instance.getUserBillingBucketDetailsGraph(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingClusterDetailsGraph', function() {
      it('should call getUserBillingClusterDetailsGraph successfully', function(done) {
        //uncomment below and update the code to test getUserBillingClusterDetailsGraph
        //instance.getUserBillingClusterDetailsGraph(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingDataSynthesisDetailsGraph', function() {
      it('should call getUserBillingDataSynthesisDetailsGraph successfully', function(done) {
        //uncomment below and update the code to test getUserBillingDataSynthesisDetailsGraph
        //instance.getUserBillingDataSynthesisDetailsGraph(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingFineTuningDetailsGraph', function() {
      it('should call getUserBillingFineTuningDetailsGraph successfully', function(done) {
        //uncomment below and update the code to test getUserBillingFineTuningDetailsGraph
        //instance.getUserBillingFineTuningDetailsGraph(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingHistory2', function() {
      it('should call getUserBillingHistory2 successfully', function(done) {
        //uncomment below and update the code to test getUserBillingHistory2
        //instance.getUserBillingHistory2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingHistoryBucket2', function() {
      it('should call getUserBillingHistoryBucket2 successfully', function(done) {
        //uncomment below and update the code to test getUserBillingHistoryBucket2
        //instance.getUserBillingHistoryBucket2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingHistoryBucketDetails', function() {
      it('should call getUserBillingHistoryBucketDetails successfully', function(done) {
        //uncomment below and update the code to test getUserBillingHistoryBucketDetails
        //instance.getUserBillingHistoryBucketDetails(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingHistoryCluster', function() {
      it('should call getUserBillingHistoryCluster successfully', function(done) {
        //uncomment below and update the code to test getUserBillingHistoryCluster
        //instance.getUserBillingHistoryCluster(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingHistoryClusterDetails', function() {
      it('should call getUserBillingHistoryClusterDetails successfully', function(done) {
        //uncomment below and update the code to test getUserBillingHistoryClusterDetails
        //instance.getUserBillingHistoryClusterDetails(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingHistoryContract', function() {
      it('should call getUserBillingHistoryContract successfully', function(done) {
        //uncomment below and update the code to test getUserBillingHistoryContract
        //instance.getUserBillingHistoryContract(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingHistoryDataSynthesis', function() {
      it('should call getUserBillingHistoryDataSynthesis successfully', function(done) {
        //uncomment below and update the code to test getUserBillingHistoryDataSynthesis
        //instance.getUserBillingHistoryDataSynthesis(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingHistoryDataSynthesisDetails', function() {
      it('should call getUserBillingHistoryDataSynthesisDetails successfully', function(done) {
        //uncomment below and update the code to test getUserBillingHistoryDataSynthesisDetails
        //instance.getUserBillingHistoryDataSynthesisDetails(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingHistoryFineTuning', function() {
      it('should call getUserBillingHistoryFineTuning successfully', function(done) {
        //uncomment below and update the code to test getUserBillingHistoryFineTuning
        //instance.getUserBillingHistoryFineTuning(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingHistoryFineTuningDetails', function() {
      it('should call getUserBillingHistoryFineTuningDetails successfully', function(done) {
        //uncomment below and update the code to test getUserBillingHistoryFineTuningDetails
        //instance.getUserBillingHistoryFineTuningDetails(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingHistoryModelEvaluation', function() {
      it('should call getUserBillingHistoryModelEvaluation successfully', function(done) {
        //uncomment below and update the code to test getUserBillingHistoryModelEvaluation
        //instance.getUserBillingHistoryModelEvaluation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingHistoryModelEvaluationDetails', function() {
      it('should call getUserBillingHistoryModelEvaluationDetails successfully', function(done) {
        //uncomment below and update the code to test getUserBillingHistoryModelEvaluationDetails
        //instance.getUserBillingHistoryModelEvaluationDetails(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingHistoryServerlessInference', function() {
      it('should call getUserBillingHistoryServerlessInference successfully', function(done) {
        //uncomment below and update the code to test getUserBillingHistoryServerlessInference
        //instance.getUserBillingHistoryServerlessInference(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingHistoryServerlessInferenceDetails', function() {
      it('should call getUserBillingHistoryServerlessInferenceDetails successfully', function(done) {
        //uncomment below and update the code to test getUserBillingHistoryServerlessInferenceDetails
        //instance.getUserBillingHistoryServerlessInferenceDetails(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingHistorySnapshot', function() {
      it('should call getUserBillingHistorySnapshot successfully', function(done) {
        //uncomment below and update the code to test getUserBillingHistorySnapshot
        //instance.getUserBillingHistorySnapshot(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingHistorySnapshotDetails', function() {
      it('should call getUserBillingHistorySnapshotDetails successfully', function(done) {
        //uncomment below and update the code to test getUserBillingHistorySnapshotDetails
        //instance.getUserBillingHistorySnapshotDetails(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingHistoryVm2', function() {
      it('should call getUserBillingHistoryVm2 successfully', function(done) {
        //uncomment below and update the code to test getUserBillingHistoryVm2
        //instance.getUserBillingHistoryVm2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingHistoryVmDetails2', function() {
      it('should call getUserBillingHistoryVmDetails2 successfully', function(done) {
        //uncomment below and update the code to test getUserBillingHistoryVmDetails2
        //instance.getUserBillingHistoryVmDetails2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingHistoryVmSubResourceGraph2', function() {
      it('should call getUserBillingHistoryVmSubResourceGraph2 successfully', function(done) {
        //uncomment below and update the code to test getUserBillingHistoryVmSubResourceGraph2
        //instance.getUserBillingHistoryVmSubResourceGraph2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingHistoryVmTotalCosts', function() {
      it('should call getUserBillingHistoryVmTotalCosts successfully', function(done) {
        //uncomment below and update the code to test getUserBillingHistoryVmTotalCosts
        //instance.getUserBillingHistoryVmTotalCosts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingHistoryVolume2', function() {
      it('should call getUserBillingHistoryVolume2 successfully', function(done) {
        //uncomment below and update the code to test getUserBillingHistoryVolume2
        //instance.getUserBillingHistoryVolume2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingHistoryVolumeDetails2', function() {
      it('should call getUserBillingHistoryVolumeDetails2 successfully', function(done) {
        //uncomment below and update the code to test getUserBillingHistoryVolumeDetails2
        //instance.getUserBillingHistoryVolumeDetails2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingModelEvaluationDetailsGraph', function() {
      it('should call getUserBillingModelEvaluationDetailsGraph successfully', function(done) {
        //uncomment below and update the code to test getUserBillingModelEvaluationDetailsGraph
        //instance.getUserBillingModelEvaluationDetailsGraph(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingServerlessInferenceDetailsGraph', function() {
      it('should call getUserBillingServerlessInferenceDetailsGraph successfully', function(done) {
        //uncomment below and update the code to test getUserBillingServerlessInferenceDetailsGraph
        //instance.getUserBillingServerlessInferenceDetailsGraph(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingSnapshotDetailsGraph', function() {
      it('should call getUserBillingSnapshotDetailsGraph successfully', function(done) {
        //uncomment below and update the code to test getUserBillingSnapshotDetailsGraph
        //instance.getUserBillingSnapshotDetailsGraph(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingVmDetailsGraph2', function() {
      it('should call getUserBillingVmDetailsGraph2 successfully', function(done) {
        //uncomment below and update the code to test getUserBillingVmDetailsGraph2
        //instance.getUserBillingVmDetailsGraph2(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserBillingVolumeDetailsGraph', function() {
      it('should call getUserBillingVolumeDetailsGraph successfully', function(done) {
        //uncomment below and update the code to test getUserBillingVolumeDetailsGraph
        //instance.getUserBillingVolumeDetailsGraph(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserVmBillingEvents', function() {
      it('should call getUserVmBillingEvents successfully', function(done) {
        //uncomment below and update the code to test getUserVmBillingEvents
        //instance.getUserVmBillingEvents(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserVolumeBillingEvents', function() {
      it('should call getUserVolumeBillingEvents successfully', function(done) {
        //uncomment below and update the code to test getUserVolumeBillingEvents
        //instance.getUserVolumeBillingEvents(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putOrganizationThreshold', function() {
      it('should call putOrganizationThreshold successfully', function(done) {
        //uncomment below and update the code to test putOrganizationThreshold
        //instance.putOrganizationThreshold(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
